### ISSUE TITLE
Format du code

### ISSUE THREAD

**Issue by nioperas06** [moufking/tp-angular#1]
Exemple:
```
import {Routes} from "@angular/router";
import {LibraryComponent} from './library/library.component';
import {SearchComponent} from './search/search.component';
import {BookComponent} from './book/book.component';
import {BookListComponent} from './book-list/book-list.component';


export const routes: Routes = [

    {path: 'library',component: LibraryComponent},
    {path: 'book/:bookId',component: BookComponent },
    {path: 'search',component: SearchComponent },
    {path: '', redirectTo: 'library', pathMatch: 'full'}



];
```

- [ ] Trop de lignes inutiles 👎 
- [ ] Dans les imports, tu mélanges " et '. 👎 
- [ ] Manque d'espace dans le code 👎 
Tu aurais pu écrire comme ceci:
```{ path: 'library', component: LibraryComponent },```

Et cela se répète dans plusieurs fichiers (book.ts) par exemple. 
- [ ] Choisis un nombre d'identation. Jette un coup d'oeil à [editorconfig](https://editorconfig.org/)

**Comment by moufking** [comment]
déja  fait
