### ISSUE TITLE
Que fait cette ligne de code?

### ISSUE THREAD

**Issue by nioperas06** [moufking/tp-angular#13]
```
this.books.push(Object.assign(new Book(null, null, null, null, null, null, null, null, null, null), savedBook));
```

**Comment by moufking** [comment]
elle ajoute une nouveau livre a la fin de l'objet

**Comment by nioperas06** [comment]
C'est quoi la définition de la méthode `assign`? Que fait `Object.assign(new Book(null, null, null, null, null, null, null, null, null, null)` ?

**Comment by nioperas06** [comment]
Pourquoi tous ces `null`?

**Comment by moufking** [comment]
c'est pour recevoir ce que savedBook lui envoi .C'est a dire ajoute le contenu de savedBook  dans le new book. Ainsi à la fin le new book  n'aura plus de valeur null mais plutot les valueur contenu dans saveBook

**Comment by moufking** [comment]
c'est null pour recevoir le contenu de savebook

**Comment by nioperas06** [comment]
Pourquoi on doit procéder ainsi; ce n'est pas forcément très joli.
