### ISSUE TITLE
Réflexion

### ISSUE THREAD

**Issue by nioperas06** [moufking/tp-angular#14]
Tu as utilisé LocalStorage pour le stockage des données. À présent regardes [Cache API](https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/cache-api). Dis-moi si on peut l'utiliser comme alternative au LocalStorage? Si oui, fais-le 😄

**Comment by nioperas06** [comment]
Si non, tu justifies 🤔

**Comment by moufking** [comment]
cela est possible car Cache Api permet aussi de réaliser des stockage des donnée.Je l'ai implémenté mais j'ai une erreur que j'ai pas pu encore resoudre
